DROP TABLE IF EXISTS CUSTOMER_CHAT;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS AGENT;
DROP TABLE IF EXISTS XWINDOW;

CREATE TABLE USER (
   user_id VARCHAR(20) PRIMARY KEY,
   name VARCHAR(30),
   password VARCHAR(30),
   amount_debt DECIMAL(15,2));

CREATE TABLE AGENT (
    agent_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20) NOT NULL
);

CREATE TABLE MESSAGE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  user_id VARCHAR(20),
  is_user_message BIT,
  agent_id INT,
  message VARCHAR(500) NOT NULL,
  message_time TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES USER(user_id),
  FOREIGN KEY (agent_id) REFERENCES AGENT(agent_id)
);

CREATE TABLE XWINDOW (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    user_id VARCHAR(20),
    agent_id INT,
    FOREIGN KEY (user_id) REFERENCES USER(user_id),
    FOREIGN KEY (agent_id) REFERENCES AGENT(agent_id)
)

